### What is outlier?
An outlier is a data point that :
1) is a noise in dataset
2) deviates from normal distribution of dataset. 
3) distant from all other observations (lies outside the overall distribution of the dataset)

### Why to consider outlier detection
1. It affect algorithm performance as in presence of outlier, algorithm tries to fit noise present in data

### Should I handle Outlier?

1) Should be keep or removed from problem based on problem. 
Example-1: Fraud detection, anomaly detection - should be kept in the dataset
Example-2: Predictive or classification problem - should be removed

### Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### What are the criteria to identify an outlier?

1. Data point that falls outside of 1.5 times of an interquartile range above the 3rd quartile and below the 1st quartile
2. Data point that falls outside of 3 standard deviations. we can use a z score and if the z score falls outside of 2 standard deviation

### What is the reason for an outlier to exists in a dataset?

1. Variability in the data
2. An experimental measurement error
3. Manual error
4. Intentional

### What are the impacts of having outliers in a dataset?

1. It causes various problems during our statistical analysis and cause poor accuracy
2. It may cause a significant impact on the mean and the standard deviation

### Various ways of finding the outlier.
1. Using scatter plots
2. Box plot
3. using z score
4. using the IQR interquantile range
5. Eliptical method



In [33]:
dataset= [11,10,12,14,12,15,14,13,15,102,12,14,17,19,107, 10,13,12,14,12,108,12,11,14,13,15,10,15,12,10,14,13,15,10]

In [34]:
#dataset = np.random.randint(1,1000,50)
#dataset

## Detecting outlier using Z score

### Using Z score

Formula for Z score = (Observation — Mean)/Standard Deviation

z = (X — μ) / σ

In [38]:
outliers=[]
def detect_outliers(data):
    
    threshold=3
    mean = np.mean(data)
    std =np.std(data)
    
    
    for i in data:
        z_score= (i - mean)/std 
        if np.abs(z_score) > threshold:
            outliers.append(i)
    return outliers

In [39]:
outlier_pt=detect_outliers(dataset)

In [40]:
outlier_pt

[102, 107, 108]

## InterQuantile Range

75%- 25% values in a dataset

### Steps
#### 1. Arrange the data in increasing order
#### 2. Calculate first(q1) and third quartile(q3)
#### 3. Find interquartile range (q3-q1)
#### 4.Find lower bound q1*1.5
#### 5.Find upper bound q3*1.5

Anything that lies outside of lower and upper bound is an outlier

In [41]:
## Perform all the steps of IQR
sorted(dataset)

[10,
 10,
 10,
 10,
 10,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 15,
 15,
 15,
 17,
 19,
 102,
 107,
 108]

In [42]:
quantile1, quantile3= np.percentile(dataset,[25,75])

In [43]:
print(quantile1,quantile3)

12.0 15.0


In [44]:
## Find the IQR

iqr_value=quantile3-quantile1
print(iqr_value)

3.0


In [46]:
## Find the lower bound value and the higher bound value

lower_bound_val = quantile1 -(1.5 * iqr_value) 
upper_bound_val = quantile3 +(1.5 * iqr_value) 

In [47]:
print(lower_bound_val,upper_bound_val)

7.5 19.5


In [51]:
dataset > upper_bound_val

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [61]:
dataset < lower_bound_val

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [76]:
outlier_indices = np.where((dataset > upper_bound_val)==True)
outlier_indices

(array([ 9, 14, 20], dtype=int64),)

In [97]:
print('outliers:', [dataset[i] for i in outlier_indices[0]])

outliers: [102, 107, 108]


### DONE